version: '3.8'

services:
  mysql-db:
    image: mysql:8.0.27  # MySQL 8.0 版本（可换成 5.7）8.0.27
    platform: linux/amd64
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel
      MYSQL_USER: user
      MYSQL_PASSWORD: 2875968600Jia
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 20s

  springboot-app:
    build: .
    container_name: springboot-container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/travel?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 2875968600Jia
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data:
