name: "ZAP DAST Security Scan"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        run: echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin

      - name: Pull OWASP ZAP Docker Image
        run: docker pull zaproxy/zap-stable

      - name: Run OWASP ZAP Scan
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          mkdir -p zap-reports && chmod -R 777 zap-reports
          docker run --rm --user root -v $(pwd)/zap-reports:/zap/wrk zaproxy/zap-stable \
          zap-baseline.py -t "$EC2_HOST" -r /zap/wrk/zap_baseline_report.html -z \
          "pscan.disable 10049; spider.exclude $EC2_HOST/robots.txt $EC2_HOST/sitemap.xml" || true
          ls -l zap-reports/

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: ./zap-reports/zap_baseline_report.html
