name: DAST Scan

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Web Application
        run: |
          docker-compose up -d  # Start your web service
          sleep 30  # Wait for 30 seconds to ensure the service is up

      - name: Run OWASP ZAP DAST Scan
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: "http://localhost:8080"  # Replace with your web application URL
          cmd_options: "-a"  # Enable active scan
          rules_file_name: ".zap/rules.tsv"  # Optional, define custom rules

      - name: Parse ZAP Scan Results
        if: always()
        run: |
          cat report_html.html || echo "No report generated"

      - name: Upload Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-scan-report
          path: report_html.html
