name: "ZAP DAST Security Scan"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Docker Hub Mirror (Aliyun)
        run: |
          sudo mkdir -p /etc/docker
          echo '{ "registry-mirrors": ["https://registry.cn-hangzhou.aliyuncs.com"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Pull OWASP ZAP Docker Image
        run: docker pull zaproxy/zap-stable

      - name: Run OWASP ZAP with POST Request
        run: |
          mkdir -p zap-reports
          docker run --rm --user root -v $(pwd)/zap-reports:/zap/wrk \
          -v $(pwd)/zap-scripts:/zap/scripts zaproxy/zap-stable \
          zap-full-scan.py -t "http://18.143.182.252:8080/api/auth/register" \
          --hook /zap/scripts/post_request.py \
          -r /zap/wrk/zap-report.html || true

          echo "Checking generated report..."
          ls -l zap-reports/

      - name: Upload Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: zap-reports/zap-report.html
          retention-days: 5
          if-no-files-found: warn
