name: "ZAP DAST Security Scan"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        run: echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin

      - name: Pull OWASP ZAP Docker Image
        run: docker pull zaproxy/zap-stable

      - name: Create Custom Hook Script
        run: |
          mkdir -p zap-scripts
          cat <<EOF > zap-scripts/custom_hooks.py
          def zap_started(zap, target):
              print("ZAP started, configuring rules...")
              # 忽略 10049 警告
              zap.pscan.disable_scanners("10049")
              # 忽略特定 URL
              zap.spider.exclude_from_scan(".*robots\\.txt.*")
              zap.spider.exclude_from_scan(".*sitemap\\.xml.*")
              print("Configuration applied.")
          EOF
          chmod +x zap-scripts/custom_hooks.py
          ls -l zap-scripts/

      - name: Run OWASP ZAP Scan
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          mkdir -p zap-reports && chmod -R 777 zap-reports
          docker run --rm -v $(pwd)/zap-reports:/zap/wrk zaproxy/zap-stable \
          zap-full-scan.py -t "$EC2_HOST" -r /zap/wrk/zap_full_scan_report.html \
          -z "-config spider.maxDepth=5" \
          -z "-config spider.threadCount=5" \
          -z "-config connection.userAgent=Mozilla/5.0"
          ls -l zap-reports/

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: ./zap-reports/zap_baseline_report.html
